organization: mautic
holobytes:
  - evolvingStickerId: cm1ti4x4c57560cjq2styaitm
    icon: avocado
    alias: hacktober-2024

# First time contributor badge
stickers:
  - id: cmc38nn5r166207icbleca9jp
    name: First Contribution
    alias: first-contribution

